"use client";

import { useRef, useState } from "react";
import { Check, Copy, FileText } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Markdown } from "@/components/ui/markdown";

type Props = {
  report: string;
};

/**
 * Rendered investment report.
 *
 * Uses the shared {@link Markdown} renderer so generated reports match the chat
 * transcript exactly (the previous `prose` classes had no effect because the
 * Tailwind typography plugin is not installed).
 */
export function ReportViewer({ report }: Props) {
  const [copied, setCopied] = useState(false);
  const timeoutRef = useRef<number | null>(null);

  async function copy() {
    try {
      await navigator.clipboard.writeText(report);
    } catch {
      // Clipboard access can be denied by the browser; the report stays
      // selectable so the user can still copy it manually.
      return;
    }

    setCopied(true);

    if (timeoutRef.current !== null) window.clearTimeout(timeoutRef.current);

    timeoutRef.current = window.setTimeout(() => setCopied(false), 2000);
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle as="h2">Report content</CardTitle>

        <Button variant="secondary" size="sm" onClick={copy}>
          {copied ? (
            <Check className="size-3.5 text-gain" aria-hidden="true" />
          ) : (
            <Copy className="size-3.5" aria-hidden="true" />
          )}
          {copied ? "Copied" : "Copy report"}
        </Button>
      </CardHeader>

      <CardBody>
        <p role="status" className="sr-only">
          {copied ? "Report copied to the clipboard." : ""}
        </p>

        <div className="flex items-start gap-2 text-caption text-subtle-foreground">
          <FileText className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
          <span>Generated by the backend report endpoint.</span>
        </div>

        <div className="mt-4">
          <Markdown>{report}</Markdown>
        </div>
      </CardBody>
    </Card>
  );
}
