"use client";


import { Component, type ErrorInfo, type ReactNode, useRef, useState } from "react";
import { Check, Copy, FileText } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Markdown } from "@/components/ui/markdown";

type Props = {
  report: string;
};

type ReportErrorBoundaryState = {
  hasError: boolean;
};

class ReportErrorBoundary extends Component<
  { children: ReactNode },
  ReportErrorBoundaryState
> {
  state: ReportErrorBoundaryState = { hasError: false };

  static getDerivedStateFromError(): ReportErrorBoundaryState {
    return { hasError: true };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    console.error("[report-viewer] report rendering failed", error, errorInfo);
  }

  private retry = () => {
    this.setState({ hasError: false });
  };

  render() {
    if (this.state.hasError) {
      return (
        <Card role="alert">
          <CardBody className="space-y-4">
            <p>Unable to display this report.</p>
            <Button type="button" variant="secondary" onClick={this.retry}>
              Try again
            </Button>
          </CardBody>
        </Card>
      );
    }

    return this.props.children;
  }
}

function ReportViewerContent({ report }: Props) {
  const [copied, setCopied] = useState(false);
  const timeoutRef = useRef<number | null>(null);

  async function copy() {
    try {
      await navigator.clipboard.writeText(report);
    } catch {
      // Clipboard access can be denied by the browser; the report stays
      // selectable so the user can still copy it manually.
      return;
    }

    setCopied(true);

    if (timeoutRef.current !== null) window.clearTimeout(timeoutRef.current);

    timeoutRef.current = window.setTimeout(() => setCopied(false), 2000);
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle as="h2">Report content</CardTitle>

        <Button variant="secondary" size="sm" onClick={copy}>
          {copied ? (
            <Check className="size-3.5 text-gain" aria-hidden="true" />
          ) : (
            <Copy className="size-3.5" aria-hidden="true" />
          )}
          {copied ? "Copied" : "Copy report"}
        </Button>
      </CardHeader>

      <CardBody>
        <p role="status" className="sr-only">
          {copied ? "Report copied to the clipboard." : ""}
        </p>

        <div className="flex items-start gap-2 text-caption text-subtle-foreground">
          <FileText className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
          <span>Generated by the backend report endpoint.</span>
        </div>

        <div className="mt-4">
          <Markdown>{report}</Markdown>
        </div>
      </CardBody>
    </Card>
  );
}

export function ReportViewer({ report }: Props) {
  return (
    <ReportErrorBoundary>
      <ReportViewerContent report={report} />
    </ReportErrorBoundary>
  );
}
