"""
Investment report model.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True)
class InvestmentReport:
    """
    Final report generated by the Report Writer Agent.
    """

    company: str
    title: str
    body: str

    @property
    def word_count(self) -> int:
        return len(self.body.split())